config/routes.rb
Rails.application.routes.draw do
  match '/auth/sso/authorize' => 'auth#authorize', via: :all
  match '/auth/sso/access_token' => 'auth#access_token', via: :all
  match '/auth/sso/user' => 'auth#user', via: :all
  match '/oauth/token' => 'auth#access_token', via: :all

  get 'auth/:provider/callback', to: 'social_sessions#create'
  get 'mechat/index'

  namespace :admin do
    resources :media
    resources :games
    resources :categories
    resources :products
    resources :pricing_plans
    resources :users
    resources :subscriptions
    resources :genres
    root to: "media#index"
  end

  namespace :api do
    scope :v1 do
      resource :session, only: [:create, :destroy]
      resource :user, only: [:show]
      resources :categories, only: [:index, :show] do
        member do
          resources :media, only: [:index, :show], controller: 'category_media'
        end
      end
      resources :media, only: [:index, :show]
    end
  end

  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations'
                                  }

  devise_scope :user do
    get 'profile' => 'users/registrations#profile'

    get 'users/change_password' => 'users/registrations#change_password'

    put 'users/change_password' => 'users/registrations#change_password'

    post 'users/update_avatar' => 'users/registrations#update_avatar'

    post 'users/start_free_trial' => 'users/registrations#start_free_trial'
  end

  root 'pages#index'
  get 'purchases', to: 'dashboard#purchases', as: 'purchases'
  get 'index', to: 'pages#index', as: 'index' # landing page
  get 'events', to: 'pages#events', as: 'events'

  post 'schedule', to: 'schedules#index'
  post 'schedule/:show', to: 'schedules#show'
  get 'schedule/video_feed', to: 'schedules#video_feed'

  resources :products
  resources :categories, only: [:index, :show] do
    resources :media, only: [:index]
  end
  get 'media/:number', to: 'media#show', as: 'media'
  resource :checkout, only: :create
  resources :orders, only: [:new, :create]
  resources :favorite_media, only: [:create, :destroy]
  resources :subscriptions
  resources :ebooks

  get 'music', to: 'categories#music'
  post 'music', to: 'categories#music'
  get 'music/more_musics', to: 'categories#more_musics'

  get 'search', to: 'search#index', as: 'search'
  get 'user_info', to: 'user_info#show'
  
  match '*path', to: 'auth#cors_options', via: :options

  get '*unmatched', to: 'application#not_found'

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :title, presence: true
  has_many :media_categories
  has_many :media, through: :media_categories
  has_many :games, through: :media_categories, foreign_key: :medium_id

  belongs_to :category
  has_many :categories

  mount_uploader :picture, PictureUploader, mount_on: :image

  # mpx compatibility
  def thumbnail_url
    self_image = picture.present? ? picture_url : image_url
    return self_image if self_image
    medium = media.where('image IS NOT NULL').limit(1).first
    medium.try :thumbnail_url
  end

  def self.root_categories
    Category.where(category_id: nil).select { |x| !(x.title =~ /books|games/i) }
  end
end

app/models/mpx/category.rb
class MPX::Category < MPX::RemoteResource
  ENDPOINT = 'http://data.media2.theplatform.com/media/data/Category'.freeze
  SCHEMA = '1.0'.freeze
  LOCAL = 'Category'.freeze

  def self.root_categories
    MPX::Category.all.select do |c|
      c.attributes['plcategory$parentId'].empty? &&
        !(c.attributes['title'].to_s =~ /books|games/i)
    end
  end

  def title
    attributes.title.to_s.sub(/\A\w--/, '')
  end

  def media(params = {})
    @media ||= MPX::Media.all(params.merge(byCategoryIds: number))
  end

  def categories
    @categories ||= MPX::Category.all.select do |cat|
      cat.attributes['plcategory$parentId'] == id
    end
  end

  def thumbnail_url
    return description if description.present?
    @thumbnail_url ||= media.find { |m| m.thumbnail_url.present? }.try :thumbnail_url
  end
end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Category.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Category.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/api/categories_controller.rb
class Api::CategoriesController < Api::BaseController
  def index
    categories = Category.includes(:category, :categories)
                         .order('categories.order DESC')
                         .page(page)
                         .per(per_page)
    render json: categories, meta: pagination_dict(categories)
  end

  def show
    category = Category.where('id = :id OR number = :id', id: params[:id])
    if category.present?
      render json: category
    else
      render json: { errors: 'Category not found' }, status: 404
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate_user!

  layout 'new_layout'

  def index
    @categories = Category.root_categories
    render 'categories/index_new', layout: 'new_layout'
  end

  def show
    @category = MPX::Category.find_by_number(params[:id])
    @oan = MPX::Media.find_by_number('1428037766')
    @awe = MPX::Media.find_by_number('147013915')
    @media = @category.media.where(language: current_language).page(params[:page] || 1).per(MPX::RemoteResource::PER_PAGE)

    render 'categories/show_new'
  end

  def music
    request_str = Listing.get_medianet_uri
    page = 1
    page_size = 20
    
    if not params[:search].blank?
      title = params[:search]
      title_for_uri = title
      title_for_uri = Listing.replace_space title_for_uri
      request_str = request_str + '&method=search.gettracks' + '&title=' + title_for_uri + '&page=' + page.to_s + '&pageSize=' + page_size.to_s
    else
      request_str = request_str + '&method=search.gettracks' + '&page=' + page.to_s + '&pageSize=' + page_size.to_s
    end
      
    begin
      response = HTTParty.get(request_str, timeout: 600)
    rescue Net::ReadTimeout
      nil
    end

    track_list = JSON.parse(response.body)

    if track_list['Success'] == true && track_list['TotalResults'] > 0
      gon.success = true
      gon.track_list = track_list
      if (page - 1) * page_size + 1 <= track_list['TotalResults'] 
        gon.more_flag = true
      end 
      gon.page = page
      if not (defined?(title)).nil?
        gon.title = title
      end
    else
      gon.success = false
    end 
    # else
    #   gon.success = false
    # end

  end

  def more_musics

    title = params[:title]
    title_for_uri = title
    title_for_uri = Listing.replace_space title_for_uri

    request_str = Listing.get_medianet_uri
    
    page = params[:page].to_i + 1
    page_size = 20

    request_str = request_str + '&method=search.gettracks' + '&title=' + title_for_uri + '&page=' + page.to_s + '&pageSize=' + page_size.to_s

    begin
      response = HTTParty.get(request_str, timeout: 600)
    rescue Net::ReadTimeout
      nil
    end

    track_list = JSON.parse(response.body)

    @data = Hash.new

    if track_list['Success'] == true && track_list['TotalResults'] > 0
      @data['success'] = true
      @data['track_list'] = track_list
      if (page - 1) * page_size + track_list['ResultsReturned'] == track_list['TotalResults'] 
        @data['more_flag'] = false
      else
        @data['more_flag'] = true 
      end 
      @data['page'] = page
      @data['title'] = title
    else
      @data['success'] = false
    end 

    render json: @data
  end

  def more_musics

    title = params[:title]
    title_for_uri = title
    title_for_uri = Listing.replace_space title_for_uri

    request_str = Listing.get_medianet_uri
    
    page = params[:page].to_i + 1
    page_size = 20

    request_str = request_str + '&method=search.gettracks' + '&title=' + title_for_uri + '&page=' + page.to_s + '&pageSize=' + page_size.to_s

    begin
      response = HTTParty.get(request_str, timeout: 600)
    rescue Net::ReadTimeout
      nil
    end

    track_list = JSON.parse(response.body)

    @data = Hash.new

    if track_list['Success'] == true && track_list['TotalResults'] > 0
      @data['success'] = true
      @data['track_list'] = track_list
      if (page - 1) * page_size + track_list['ResultsReturned'] == track_list['TotalResults'] 
        @data['more_flag'] = false
      else
        @data['more_flag'] = true 
      end 
      @data['page'] = page
      @data['title'] = title
    else
      @data['success'] = false
    end 

    render json: @data
  end

end

app/views/categories/_all_media.html.erb
  <div class="cp-featured-block m60 cp-comedy-video">
    <div class="row">
      <div class="col-md-12 cp-heading-outer">
        <h2>All <%= @category.title %></h2>
      </div>
      <% is_game = @category.title.match("Games") ||(@category.category && @category.category.title.match("Games")) ? true : false %>
      <div class="col-md-12 featured-blocks <%= is_game ? 'categories-list' : 'videos-list' %> medium uk-grid uk-grid-width-small-1-2 uk-grid-width-medium-1-3 uk-grid-width-large-1-4" data-uk-grid>
          <% @media.each do |m|%>
              <div class="single-category-block">
                  <figure class="cp-thumb">
                    <% m = m.becomes(Game) if is_game  %>
                    <% if m.thumbnail_url.present? %>
                      <% if @category.title.match("Movies") %>
                        <img alt="" src="<%= m.thumbnail_url %>" class="makemetaller">
                      <% else %>
                      <img alt="" src="<%= m.thumbnail_url %>">
                      <% end %>
                    <% else %>
                      <img src="<%= asset_path('movie-placeholder.jpg') %>">
                    <% end %>
                    <figcaption class="cp-caption">
                      <a class="play-video" href="/media/<%= m.number %>">Play</a>
                    <% if !m.category_name.match("Events") %>
                       <div class="cp-text">
                          <h4><%= m.title %></h4>
                        </div>
                        <% end %>
                    </figcaption>
                  </figure>
              </div>
          <% end%>
      </div>
    </div>
  </div>
  
<% if @media.total_pages > 1%>
  <div class="row">
    <div class="col-md-12">
      <% if params[:page].to_i >= 2 %>
        <a class="btn btn-sm btn-primary" href="?page=<%= params[:page].to_i - 1 %>">
         Prev page
        </a>
      <% end %>
      <% if params[:page].to_i < @media.total_pages %>
      <div style="float:right">
        <a class="btn btn-sm btn-primary" href="?page=<%= (params[:page] || 1).to_i + 1 %>"> Next page</a>
      </div>
      <% end %>
    </div>
<% end %>

app/views/categories/_free_trial_modal.html.erb
<div id="free-trial" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Enter credit card to start "7 Day Free Trial"</h4>
      </div>
      <div class="modal-body">
        <div class="new-subscription">

              <div class="sub-panel">
                <div class="row main">
                    <%= form_for(current_user, url: users_start_free_trial_path, html: { method: :post}) do |f| %>
                    <div class="row form-row">
                      <div class="col-sm-6">
                        <div class="field">
                          <div class="field-label">First name:</div>
                          <input type="text" name="first_name" id="first_name">
                        </div>
                      </div>
                      <div class="col-sm-6">
                        <div class="field">
                          <div class="field-label">Last name:</div>
                          <input type="text" name="last_name" id="last_name">
                        </div>
                      </div>
                    </div>
                    <div class="row form-row">
                      <div class="col-sm-9">
                        <div class="field">
                          <div class="field-label">Card Number:</div>
                          <input type="text" name="first_name" id="card_number">
                        </div>
                      </div>
                      <div class="col-sm-3">
                        <div class="field">
                          <div class="field-label">CVV:</div>
                          <input type="password">
                        </div>
                      </div>
                    </div>
                    <div class="row form-row">
                      <div class="col-sm-5">
                        <div class="field">
                          <div class="field-label">Expires On Month:</div>
                          <select name="expire_month" class="form-control">
                            <% 1.upto(12) do |m| %>
                              <option value="<%= m %>"><%= m.to_s.rjust(2, '0') %></option>
                            <% end %>
                          </select>
                        </div>
                      </div>
                      <div class="col-sm-4">
                        <div class="field">
                          <div class="field-label">Year:</div>
                          <select name="expire_month" class="form-control">
                            <% year = Date.today.year.to_s[-2..-1].to_i %>
                            <% 10.times do |n| %>
                              <option value="<%= year + n %>"><%= year + n %></option>
                            <% end %>
                          </select>
                        </div>
                      </div>
                    </div>
                    <div class="row form-row checkout-row">
                      <div class="col-sm-12">
                        <div class="pull-right">
                          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                          <button type="submit" class="btn btn-default checkout-btn">Start Free Trial</button>
                        </div>
                      </div>
                    </div>
                    <% end %>
                </div>
              </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/_media_slider.html.erb
<% is_game = @category.title.match("Games") ||(@category.category && @category.category.title.match("Games")) ? true : false %>
<div class="cp-featured-block cp-comedy-video">
      <div class="row">
        <div class="col-md-12 cp-heading-outer">
          <h2>All <%= @category.title %></h2>
          <ul class="cp-listed">
              <li class="view-all"><a href="<%= category_media_path(@category.number) %>">View All</a>
              </li>
          </ul>
        </div>
      </div>
        <div class="featured-blocks <%= is_game ? 'categories-list' : 'videos-list' %> uk-slidenav-position">
            <div class="row">
              <div class="row__inner">
                <% @media.each do |m| %>
                  <div class="tile">
                    <div class="tile__media">
                      <% m = m.becomes(Game) if is_game %>
                      <% if m.thumbnail_url.present? %>
                        <% if @category.title.match("Movies") %>
                          <img alt="" src="<%= m.thumbnail_url %>" class="makemetaller">
                        <% else %>
                        <img alt="" src="<%= m.thumbnail_url %>">
                        <% end %>
                      <% else %>
                        <img src="<%= asset_path('movie-placeholder.jpg') %>">
                      <% end %>
                    </div>
                    <div class="tile__details">
                      <div class="tile__title">
                        <figcaption class="cp-caption">
                          <a class="play-video" href="/media/<%= m.number %>">Play</a>
                          <% if !m.category_name.match("Events") %>
                            <div class="cp-text">
                              <h4><%= m.title %></h4>
                            </div>
                          <% end %>
                        </figcaption>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
              <a href="" class="previous uk-slidenav uk-slidenav-contrast uk-slidenav-previous" data-uk-slider-item="previous"></a>
              <a href="" class="next uk-slidenav uk-slidenav-contrast uk-slidenav-next" data-uk-slider-item="next"></a>
            </div>
        </div>
    </div>
</div>

app/views/categories/index-rob.html.erb
<!--Banner Start-->
			<div class="cp_inner-banner">
				<div class="container">
					<div class="cp-inner-banner-holder">
						<h2>Category: <strong>Live TV</strong></h2>
						<!--Breadcrumb Start-->
						<ul class="breadcrumb">
							<li><span>Filter:</span>  <a href="#">International | News | Sports | Kids & Family</a></li>
							
						</ul><!--Breadcrumb End-->
					</div>
				</div>
			</div><!--Banner End-->
  <!--Main Content Start-->
  <div id="cp-main-content">
    <section class="cp-section pd-tb60">
      <div class="container"> 
      <!--Featured Video Block 2-->
            <div class="cp-featured-block m60">
              <div class="row">
                <div class="col-md-12 cp-heading-outer">
                  <h2>Sports Videos</h2>
                  <ul class="cp-listed">
                    <li class="view-all"><a href="category-sports.html">View All:</a></li>
                  </ul>
                </div>
                <div class="featured-blocks">
                  <div class="col-md-5 col-lg-3">
                    <figure class="cp-thumb"> <img alt="" src="images/fi-1.jpg">
                      <figcaption class="cp-caption"> <a class="play-video" href="video.html">Play</a>
                        <div class="cp-text">
                          <h4>Mini Deep Dish Pizzas </h4>
                          <ul class="cp-meta-list">
                            <li>Feb 26, 2016</li>
                            <li>by Jiana Smith, <span>19 Views</span></li>
                          </ul>
                        </div>
                      </figcaption>
                    </figure>
                  </div>
                  <div class="col-md-5 col-lg-3">
                    <figure class="cp-thumb"> <img alt="" src="images/fi-2.jpg">
                      <figcaption class="cp-caption"> <a class="play-video" href="video.html">Play</a>
                        <div class="cp-text">
                          <h4>Mini Deep Dish Pizzas</h4>
                          <ul class="cp-meta-list">
                            <li>Feb 26, 2016</li>
                            <li>by Jiana Smith, <span>27 Views</span></li>
                          </ul>
                        </div>
                      </figcaption>
                    </figure>
                  </div>
                  <div class="col-md-5 col-lg-3">
                    <figure class="cp-thumb"> <img alt="" src="images/fi-3.jpg">
                      <figcaption class="cp-caption"> <a class="play-video" href="video.html">Play</a>
                        <div class="cp-text">
                          <h4>Mini Deep Dish Pizzas </h4>
                          <ul class="cp-meta-list">
                            <li>Feb 26, 2016</li>
                            <li>by Jiana Smith, <span>44 Views</span></li>
                          </ul>
                        </div>
                      </figcaption>
                    </figure>
                  </div>
                  <div class="col-md-5 col-lg-offset-0 col-lg-3">
                    <figure class="cp-thumb"> <img alt="" src="images/fi-3.jpg">
                      <figcaption class="cp-caption"> <a class="play-video" href="video.html">Play</a>
                        <div class="cp-text">
                          <h4>Mini Deep Dish Pizzas </h4>
                          <ul class="cp-meta-list">
                            <li>Feb 26, 2016</li>
                            <li>by Jiana Smith, <span>44 Views</span></li>
                          </ul>
                        </div>
                      </figcaption>
                    </figure>
                  </div>
                </div>
              </div>
            </div>
            <!--Featured Video Block 2 End--> 
      
        <!--Outer Holder Start-->
        
        <div class="cp-outer-holder cp-featured-video">
          <div class="row">
            <div class="col-md-12 cp-heading-outer">
              <h2>Category Title</h2>
              <ul class="cp-listed">
                <li class="view-all"><a href="#">View All:</a></li>
              </ul>
            </div>
          </div>
          <div id="featured-video">
            <div class="item"> 
              <!-- Video Item Start-->
              <div class="cp-video-item">
                <figure class="cp-thumb"> <img src="images/channel-amc.png" alt="AMC - East Coast Feed">
                  <figcaption class="cp-caption"> <a href="video.html" class="play-video">Play</a> </figcaption>
                </figure>
                <div class="cp-text">
                  <h4><a href="#">AMC</a></h4>
                  <ul class="cp-meta-list">
                    <li>Live Feed EST</li>
                    <li>Languages:<span>English | Espanol | French</span></li>
                  </ul>
                </div>
              </div>
              <!-- Video Item End--> 
            </div>
            <div class="item"> 
              <!-- Video Item Start-->
              <div class="cp-video-item">
                <figure class="cp-thumb"> <img src="images/video-img-02.jpg" alt="">
                  <figcaption class="cp-caption"> <a href="video.html" class="play-video">Play</a> </figcaption>
                </figure>
                <div class="cp-text">
                 <h4><a href="#">Channel Name</a></h4>
                  <ul class="cp-meta-list">
                    <li>Live Feed EST</li>
                    <li>Languages:<span>English | Espanol | French</span></li>
                  </ul>
                </div>
              </div>
              <!-- Video Item End--> 
            </div>
            <div class="item"> 
              <!-- Video Item Start-->
              <div class="cp-video-item">
                <figure class="cp-thumb"> <img src="images/video-img-03.jpg" alt="">
                  <figcaption class="cp-caption"> <a href="video.html" class="play-video">Play</a> </figcaption>
                </figure>
                <div class="cp-text">
                  <h4><a href="#">Channel Name</a></h4>
                  <ul class="cp-meta-list">
                    <li>Live Feed EST</li>
                    <li>Languages:<span>English | Espanol | French</span></li>
                  </ul>
                </div>
              </div>
              <!-- Video Item End--> 
            </div>
            <div class="item"> 
              <!-- Video Item Start-->
              <div class="cp-video-item">
                <figure class="cp-thumb"> <img src="images/video-img-04.jpg" alt="">
                  <figcaption class="cp-caption"> <a href="video.html" class="play-video">Play</a> </figcaption>
                </figure>
                <div class="cp-text">
                  <h4><a href="#">Channel Name</a></h4>
                  <ul class="cp-meta-list">
                    <li>Live Feed EST</li>
                    <li>Languages:<span>English | Espanol | French</span></li>
                  </ul>
                </div>
              </div>
              <!-- Video Item End--> 
            </div>
            <div class="item"> 
              <!-- Video Item Start-->
              <div class="cp-video-item">
                <figure class="cp-thumb"> <img src="images/video-img-01.jpg" alt="">
                  <figcaption class="cp-caption"> <a href="video.html" class="play-video">Play</a> </figcaption>
                </figure>
                <div class="cp-text">
                 <h4><a href="#">Channel Name</a></h4>
                  <ul class="cp-meta-list">
                    <li>Live Feed EST</li>
                    <li>Languages:<span>English | Espanol | French</span></li>
                  </ul>
                </div>
              </div>
              <!-- Video Item End--> 
            </div>
            <div class="item"> 
              <!-- Video Item Start-->
              <div class="cp-video-item">
                <figure class="cp-thumb"> <img src="images/video-img-01.jpg" alt="">
                  <figcaption class="cp-caption"> <a href="video.html" class="play-video">Play</a> </figcaption>
                </figure>
                <div class="cp-text">
                 <h4><a href="#">Channel Name</a></h4>
                  <ul class="cp-meta-list">
                    <li>Live Feed EST</li>
                    <li>Languages:<span>English | Espanol | French</span></li>
                  </ul>
                </div>
              </div>
              <!-- Video Item End--> 
            </div>
            <div class="item"> 
              <!-- Video Item Start-->
              <div class="cp-video-item">
                <figure class="cp-thumb"> <img src="images/video-img-01.jpg" alt="">
                  <figcaption class="cp-caption"> <a href="video.html" class="play-video">Play</a> </figcaption>
                </figure>
                <div class="cp-text">
                 <h4><a href="#">Channel Name</a></h4>
                  <ul class="cp-meta-list">
                    <li>Live Feed EST</li>
                    <li>Languages:<span>English | Espanol | French</span></li>
                  </ul>
                </div>
              </div>
              <!-- Video Item End-->  
            </div>
            <div class="item"> 
             <!-- Video Item Start-->
              <div class="cp-video-item">
                <figure class="cp-thumb"> <img src="images/video-img-01.jpg" alt="">
                  <figcaption class="cp-caption"> <a href="video.html" class="play-video">Play</a> </figcaption>
                </figure>
                <div class="cp-text">
                 <h4><a href="#">Channel Name</a></h4>
                  <ul class="cp-meta-list">
                    <li>Live Feed EST</li>
                    <li>Languages:<span>English | Espanol | French</span></li>
                  </ul>
                </div>
              </div>
              <!-- Video Item End-->  
            </div>
          </div>
        </div>
        
        <!--Outer Holder End--> 
      </div>
    </section>
       
  <!--Main Content End-->

app/views/categories/index.html.slim
.content
  .uk-container.uk-container-center.categories
    - @categories.each do |c|
      - next if c.media.size == 0 && c.categories.size == 0
      .uk-width-1-1
        h2= c.title
      - if c.categories.any?
        .nested-categories
          - columns_count = define_columns_count(c.categories.count)
          - c.categories.in_groups_of(columns_count) do |group|
            .uk-grid
              - group.compact.each do |cat|
                div class="uk-width-1-#{columns_count}"
                  a href=category_path(cat.number)
                    - if cat.thumbnail_url.present?
                      img.uk-thumbnail src=cat.thumbnail_url
                    - else
                      img.uk-thumbnail src=asset_path('product-placeholder.jpg')
                    h5= cat.title
      .uk-grid
        - c.media(limit: 4).each_with_index do |m, i|
          - break if i == 4
          .uk-width-1-4
            a href=media_path(m.number)
              - if m.thumbnail_url.present?
                img.uk-thumbnail src=m.thumbnail_url
              - else
                img.uk-thumbnail src=asset_path('movie-placeholder.jpg')
              h5= m.title
      - if c.media.size > 4
        .uk-width-1-1
          a.uk-badge href=category_path(c.number) Show more
      hr
      br
      

app/views/categories/index_new.html.erb
<div class="category-container">
    <!--Outer Holder Start-->
    <% @categories.each do |cat| %>
      <% next unless cat.media.where(:language => current_language ).any? %>
        <div class="cp-outer-holder cp-featured-video cp-comedy-video">
          <div class="row">
            <div class="col-md-12 cp-heading-outer">
              <h2><%= cat.title %></h2>
              <ul class="cp-listed">
                  <li class="view-all"><a href="/categories/<%= cat.number %>">View All</a>
                  </li>
              </ul>
            </div>
          </div>
          <div class="videos-list uk-slidenav-position">
          
            <div class="row">
              <div class="row__inner">
                <% cat.media.where(:language => current_language ).each do |m| %>
                  <div class="tile">
                    <div class="tile__media">
                      <% if m.thumbnail_url.present? %>
                        <img alt="" src="<%= m.thumbnail_url %>" class="tile__img">
                      <% else %>
                        <img src="<%= asset_path('movie-placeholder.jpg') %>') %>" class="tile__img">
                      <% end %>
                    </div>
                    <div class="tile__details">
                      <div class="tile__title">
                        <figcaption class="cp-caption">
                          <a href="/media/<%= m.number %>" class="play-video">Play</a>
                        </figcaption>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
              <a href="" class="previous uk-slidenav uk-slidenav-contrast uk-slidenav-previous"></a>
              <a href="" class="next uk-slidenav uk-slidenav-contrast uk-slidenav-next"></a>
            </div>
          </div>
        </div>
    <% end %>
    <!--Outer Holder End-->
</div>
<% if session[:show_trial] %>
  <%= render :partial => "categories/free_trial_modal"%>
  <%= content_for :javascript do %>
    <script type="text/javascript">
      $(document).ready(function(){
        $('#free-trial').modal('show')
      });
    </script>
  <% end %>
  <% session[:show_trial] = nil %>
<% end %>

<%= content_for :javascript do %>
  <script type="text/javascript">
    $(document).ready(function(){
      var slider = new Slider()
    });
  </script>
<% end %>